### ISSUE TITLE
expectError pass doesn't mark command green

### ISSUE THREAD

**Issue by matthewkastor** [refactoror/SelBench#5]
In the test where expectError expects the error that is thrown, the test completes without the `getEval` line being marked in green. It does what we expect it to do, so it should be marked as passed. The other cases where the error is unexpected or not thrown, those `getEval` lines get marked in red which makes sense.

I'd fix it and send another pull request, but I don't know how to mark the lines as passed or failed.

**Comment by refactoror** [comment]
This has been fixed in 1.0.1.
